"""
Customer creation flow used by valid-data tests:

Test
  ↓
create_valid_customer fixture
  ↓
CustomerBuilder
  ↓
CustomerFactory
  ↓
CustomerProvisioner
  ↓
CustomerHelper
  ↓
CustomersApi
  ↓
APIClient
  ↓
HttpClient
  ↓
WooCommerce

Responsibilities:

- CustomerFactory generates valid customer data in memory.
- CustomerBuilder customizes scenario-specific fields when required.
- CustomerProvisioner sends the prepared customer data to the application.
- CustomerHelper orchestrates the domain-level API operation.
- CustomersApi exposes the WooCommerce customer endpoint.
- APIClient / HttpClient handle HTTP communication.
- WooCommerce creates and persists the customer.
- The create_valid_customer fixture validates the creation response and
  registers the created customer for cleanup.

Tests should provide only scenario-specific data. They should not generate
random customer data or perform test-data provisioning directly.
"""

import pytest
import logging

from EcommerceAPI.src.utils.bulk_ops import bulk_create_and_validate_resources
from EcommerceAPI.src.customers.validators.customer_validators import (
    assert_customer_creation_failed,
    assert_customer_exists_and_matches_api,
)
from jsonschema import validate
from tests.shared.contracts.rest.error_schema import error_schema


logger = logging.getLogger(
    __name__
)  # logger.setLevel(logging.DEBUG) --> Already set in pytest.ini

pytestmark = [
    pytest.mark.integration,
]

INVALID_EMAIL_PAYLOADS = [
    pytest.param(
        {"email": "plainaddress", "password": "TestPass1"}, 400, id="no-at-symbol"
    ),
    pytest.param(
        {"email": "@no-local-part.com", "password": "TestPass1"},
        400,
        id="missing-local-part",
    ),
    pytest.param(
        {
            "email": "Outlook Contact <outlook-contact@domain.com>",
            "password": "TestPass1",
        },
        400,
        id="name-included",
    ),
    pytest.param(
        {"email": "no-at.domain.com", "password": "TestPass1"}, 400, id="missing-at"
    ),
    pytest.param(
        {"email": "user@gmail", "password": "TestPass1"},
        400,
        id="missing-Top-Level Domain",
    ),
    pytest.param(
        {}, 400, id="missing-email-field"
    ),  # ❌ Missing email (the only required field).)
]


# ---------------------------
# 🚀 Test: Bulk Create Customers
# ---------------------------
@pytest.mark.tcid("TCID-001")
@pytest.mark.bulk
@pytest.mark.contract
@pytest.mark.regression  # Bulk creation is heavier than smoke/sanity coverage.
@pytest.mark.parametrize("qty", [1, 3, 5])
def test_bulk_create_customers(
    qty,
    customer_helper,
    customers_dao,
    create_valid_customer,
):
    """
    Verify that multiple valid customers can be created and subsequently
    retrieved consistently through both the API and database.

    This test focuses on the bulk-creation workflow and intentionally does
    not provide scenario-specific customer fields such as billing or
    shipping addresses.

    Generic valid customer data is generated by the test-data layer:

        Test
          ↓
        create_valid_customer fixture
          ↓
        CustomerBuilder
          ↓
        CustomerFactory
          ↓
        CustomerProvisioner
          ↓
        CustomerHelper / CustomersApi
          ↓
        WooCommerce

    The CustomerFactory generates the generic valid customer data required
    for creation, including identity and address data.

    Address-specific scenarios are tested separately by TCID-004. Keeping
    those scenarios out of this bulk test ensures that each test has a
    focused responsibility.

    The create_valid_customer fixture is responsible for:
        - building valid customer creation data
        - provisioning the customer through the API
        - validating the creation response
        - registering the created customer for cleanup
        - returning the created customer data

    The bulk utility is responsible for:
        - calling create_fn() exactly ``qty`` times
        - collecting the identifiers of created customers
        - invoking validate_fn() for each created customer
        - reporting validation failures

    Test flow:
        1. Create ``qty`` valid customers through the test-data fixture.
        2. Collect each customer's email as its validation identifier.
        3. Retrieve each customer through the API.
        4. Retrieve each customer from the database.
        5. Verify that API and database data match.
        6. Allow the ownership/cleanup mechanism to remove all customers
           created by this test.

    Contract coverage:
        The test is marked as CONTRACT because create_valid_customer performs
        response validation using the customer response validation layer.
    """

    # ------------------------------------------------------------------
    # Step 1 — Define how one valid customer is created
    # ------------------------------------------------------------------
    def create_fn():
        """
        Create one valid customer through the standard test-data pipeline.

        No scenario-specific fields are supplied here. The CustomerFactory
        generates the complete valid customer payload.
        """
        customer = create_valid_customer()

        email = customer["email"]
        customer_id = customer["id"]

        logger.info(
            "📦 Created customer for bulk test: ID=%r, email=%r",
            customer_id,
            email,
        )

        # The bulk utility uses the email as the validation identifier.
        # Metadata is retained for logging/debugging consistency.
        return email, {
            "id": customer_id,
            "resource_type": "customers",
        }

    # ------------------------------------------------------------------
    # Step 2 — Define how one created customer is validated
    # ------------------------------------------------------------------
    def validate_fn(email):
        """
        Verify that the created customer exists and matches the database.

        Validation is intentionally performed after all requested customers
        have been created by the bulk utility.
        """

        # Retrieve customer through the API.
        api_customers = customer_helper.list_customers_paginated(
            email=email,
        )

        # Retrieve the same customer from the database.
        db_customer = customers_dao.get_customer_by_email(
            email=email,
        )

        # Verify API and database consistency.
        assert_customer_exists_and_matches_api(
            api_customers,
            email,
            db_customer,
        )

    # ------------------------------------------------------------------
    # Step 3 — Run the bulk create + validate workflow
    # ------------------------------------------------------------------
    bulk_create_and_validate_resources(
        create_fn=create_fn,
        validate_fn=validate_fn,
        qty=qty,
        label="customers",
    )


# ---------------------------
# ⚠️ Test: Edge Cases for Bulk Create
# ---------------------------
@pytest.mark.tcid("TCID-002")
@pytest.mark.bulk
@pytest.mark.negative
@pytest.mark.regression  # Bulk is heavy → NOT sanity/smoke
# @pytest.mark.skip(
#     reason="Edge case validation for qty=0 and qty=101; run manually when needed"
# )
@pytest.mark.parametrize("qty", [0, 101])
def test_bulk_create_customers_edge_cases(
    qty, customer_helper, customers_dao, create_valid_customer
):
    """
    Edge case test for bulk creation.

    Runs the bulk utility with extreme quantities (0 and 101)
    to ensure the framework handles boundary conditions correctly.

    Fixture responsibilities:
        - POST validation
        - response structure validation
        - automatic cleanup registration
    """

    # ------------------------
    # ✅ Create function
    # ------------------------
    # Called by the bulk utility to create one customers.
    # The fixture already performs POST validation and cleanup registration.
    def create_fn():
        customer = (
            create_valid_customer()
        )  # Default: skip_cleanup=False, validate_response=True

        email = customer["email"]
        customer_id = customer["id"]

        # 📦 Return identifiers and metadata (for teardown registration). Email: used as identifier to later validate
        # that customers exists. Metadata (like ID) is optional, but useful for debugging or future logging.
        return email, {"id": customer_id, "resource_type": "customers"}

    # ------------------------
    # ✅ Validate function
    # ------------------------
    # It encapsulates/summarize the logic to check that the created customers is visible via GET /customers and matches
    # DB (via DAO).
    def validate_fn(email):
        """
        Validates that the customers:
        - API GET /customers can find the customers.
        - The response is valid JSON/schema.
        - The data matches what’s stored in the DB.
        Args:
            email (str): Unique identifier used to search for the customers
        """
        # API fetch
        api_customers = customer_helper.list_customers_paginated(email=email)

        # DB fetch
        db_customer = customers_dao.get_customer_by_email(email=email)

        # API + DB validation
        assert_customer_exists_and_matches_api(
            api_customers,
            email,
            db_customer,
        )

    # -------------------------------------------------------
    # 🚀 Run the bulk utility: create + validate + teardown
    # -------------------------------------------------------
    bulk_create_and_validate_resources(
        create_fn=create_fn,
        validate_fn=validate_fn,
        qty=qty,
        label=f"customer_edge_case_{qty}",
    )


# ---------------------------
# 🧪 Test: Minimal Customer Creation
# ---------------------------
@pytest.mark.tcid("TCID-003")
@pytest.mark.sanity
@pytest.mark.smoke  # smoke ✔ (VERY important endpoint)
@pytest.mark.contract
def test_create_single_customer_with_email_and_password_only(
    customer_helper, customers_dao, create_valid_customer
):
    """
    Create a customer using the minimum valid payload.

    Test-data setup is handled by the `create_valid_customer` fixture:

        Fixture
          ↓
        CustomerBuilder
          ↓
        CustomerFactory
          ↓
        CustomerProvisioner
          ↓
        CustomerHelper / CustomersApi
          ↓
        WooCommerce

    The fixture:
        - builds a valid customer with the minimum required fields
        - provisions the customer through the API
        - validates the creation response
        - registers the created customer for cleanup
        - returns the created customer data

    Test flow:
        1. Create a customer using the valid-data fixture.
        2. Fetch the customer through the API.
        3. Fetch the customer from the database.
        4. Verify that API and database data match.

    The test does not generate test data itself because test-data
    generation and provisioning belong to the fixture/data layer.
    """

    # ------------------------------------------------------------------
    # Step 1 — Arrange: create a valid customer
    # ------------------------------------------------------------------
    logger.info("🛠 Creating a minimal valid customer via the test-data fixture.")

    customer = create_valid_customer()

    customer_id = customer["id"]
    email = customer["email"]

    # ------------------------------------------------------------------
    # Step 2 — Assert: verify API and database consistency
    # ------------------------------------------------------------------
    api_customers = customer_helper.list_customers_paginated(email=email)

    db_customer = customers_dao.get_customer_by_email(email=email)

    assert_customer_exists_and_matches_api(
        api_customers,
        email,
        db_customer,
    )

    logger.info(
        "🎯 Full validation complete for customer ID: %r",
        customer_id,
    )


# ---------------------------------------------------------------------------
# Scenario data for TCID-004
# ---------------------------------------------------------------------------
# These are explicit address scenarios, not generated test identities.
#
# CustomerFactory remains responsible for generating the customer's:
#   - email
#   - password
#   - username
#   - top-level first_name / last_name
#
# Billing/shipping addresses are supplied as complete objects because an
# explicit address override replaces the Factory's generated address.
ADDRESS_PAIRS = [
    pytest.param(
        {
            "first_name": "Madrid",
            "last_name": "Customer",
            "address_1": "Calle Mayor 10",
            "city": "Madrid",
            "state": "MADRID",
            "postcode": "28013",
            "country": "SPAIN",
        },
        {
            "first_name": "Austin",
            "last_name": "Customer",
            "address_1": "123 Test St",
            "city": "Austin",
            "state": "NY",
            "postcode": "73301",
            "country": "US",
        },
        id="spain-billing-us-shipping",
    ),
    pytest.param(
        {
            "first_name": "Berlin",
            "last_name": "Customer",
            "address_1": "Teststrasse 10",
            "city": "Berlin",
            "state": "N/A",
            "postcode": "10115",
            "country": "GERMANY",
        },
        {
            "first_name": "Bologna",
            "last_name": "Customer",
            "address_1": "Via Roma 10",
            "city": "Bologna",
            "state": "BOLOGNA",
            "postcode": "40121",
            "country": "ITALY",
        },
        id="germany-billing-italy-shipping",
    ),
]


@pytest.mark.tcid("TCID-004")
@pytest.mark.regression
@pytest.mark.contract
# @pytest.mark.skip(
#     reason="Billing/shipping fields optional — no functional difference tested."
# )
@pytest.mark.parametrize("billing, shipping", ADDRESS_PAIRS)
def test_create_customer_with_varied_addresses(
    customer_helper,
    customers_dao,
    billing,
    shipping,
    create_valid_customer,
):
    """
    Create customers with different billing and shipping addresses.

    Test-data setup is handled by the ``create_valid_customer`` fixture.
    The test provides only the scenario-specific billing and shipping
    data required for this test case.

    The fixture is responsible for:
        - CustomerBuilder
        - CustomerFactory
        - CustomerProvisioner
        - POST /customers
        - creation response validation
        - cleanup registration

    CustomerFactory remains responsible for generating the customer's
    generic identity data such as email, password, username, and
    top-level first/last name.

    Test flow:
        1. Create a customer with the parameterized addresses.
        2. Fetch the customer through the API.
        3. Fetch the customer from the database.
        4. Verify that API and database data match.

    Faker is intentionally not used here. Random test-data generation
    belongs to the CustomerFactory, while this test owns only the
    business scenario variations.
    """

    logger.debug("📦 Billing data: %s", billing)
    logger.debug("📦 Shipping data: %s", shipping)

    # ------------------------------------------------------------------
    # Step 1 — Arrange: create customer with scenario-specific addresses
    # ------------------------------------------------------------------
    logger.info(
        "🛠 Creating a customer with parameterized billing and shipping addresses."
    )

    customer = create_valid_customer(
        billing=billing,
        shipping=shipping,
    )

    customer_id = customer["id"]
    email = customer["email"]

    # ------------------------------------------------------------------
    # Step 2 — Assert: verify API and database consistency
    # ------------------------------------------------------------------
    api_customers = customer_helper.list_customers_paginated(email=email)

    db_customer = customers_dao.get_customer_by_email(email=email)

    assert_customer_exists_and_matches_api(
        api_customers,
        email,
        db_customer,
    )

    logger.info(
        "🎯 Full validation complete for customer ID: %r",
        customer_id,
    )


@pytest.mark.tcid("TCID-005")
@pytest.mark.negative
@pytest.mark.contract  # validates error_schema → contract ✔
@pytest.mark.regression
@pytest.mark.parametrize("payload, expected_status_code", INVALID_EMAIL_PAYLOADS)
def test_create_customer_email_field_validation(
    customer_api_raw,
    payload,
    expected_status_code,
):
    """
    Verify that customer creation rejects invalid email values.

    This is an intentional negative test and therefore bypasses the
    valid-data test-data pipeline.

    The supplied payload is the test scenario itself:

        Test
          ↓
        Raw API Client
          ↓
        POST /customers
          ↓
        WooCommerce
          ↓
        HTTP 400

    Test flow:
        1. Send POST /customers with an invalid email payload.
        2. Verify the expected HTTP 400 response.
        3. Validate the error response against the error contract schema.

    The valid-data Factory/Builder/Provisioner pipeline is intentionally
    not used because this test must send invalid data.
    """

    email = payload.get("email")

    logger.info(
        "🧪 Testing customer creation with invalid email: %r",
        email,
    )

    # ------------------------------------------------------------------
    # Step 1 — Act: send intentionally invalid payload
    # ------------------------------------------------------------------
    http_response = customer_api_raw.post(
        endpoint="customers",
        payload=payload,
    )

    response = http_response.json

    # ------------------------------------------------------------------
    # Step 2 — Assert: transport-level failure
    # ------------------------------------------------------------------
    assert http_response.status_code == expected_status_code

    # ------------------------------------------------------------------
    # Step 3 — Assert: error contract
    # ------------------------------------------------------------------
    validate(
        instance=response,
        schema=error_schema,
    )

    logger.info(
        "✅ Proper error returned for payload: %s → %s: %s",
        payload,
        response["code"],
        response["message"],
    )


@pytest.mark.tcid("TCID-006")
@pytest.mark.negative
@pytest.mark.contract
@pytest.mark.regression
def test_create_customer_fail_for_existing_email(
    create_valid_customer,
    customer_api_raw,
    customer_helper,
    customers_dao,
):
    """
    Verify that customer creation rejects an email address that already exists.

    This test intentionally combines two different test-data flows:

    1. Valid test-data setup:
       create_valid_customer()
           ↓
       CustomerBuilder
           ↓
       CustomerFactory
           ↓
       CustomerProvisioner
           ↓
       CustomerHelper / CustomersApi
           ↓
       WooCommerce

       The fixture creates the original customer and registers it for cleanup.

    2. Negative operation under test:
       Test
         ↓
       Raw API Client
         ↓
       POST /customers with the existing email
         ↓
       WooCommerce
         ↓
       HTTP 400

    The duplicate-email payload is intentionally constructed inside the test
    because it represents the invalid scenario being tested. It must not go
    through the valid-data Factory/Builder pipeline.

    Test flow:
        1. Create a valid customer through the test-data fixture.
        2. Extract the generated email from the created customer.
        3. Attempt to create another customer using the same email.
        4. Verify that WooCommerce returns HTTP 400.
        5. Validate the duplicate-email error response.
        6. Verify that the original customer still exists in the API.
        7. Verify that the original customer still matches the database record.
        8. Validate the error response against the error contract schema.

    Cleanup:
        The original customer is owned by this test and is automatically
        registered for cleanup by create_valid_customer().
    """

    # ------------------------------------------------------------------
    # Step 1 — Arrange: create a valid customer
    # ------------------------------------------------------------------
    logger.info(
        "🛠 Creating a valid customer to establish the duplicate-email scenario."
    )

    existing_customer = create_valid_customer()

    email = existing_customer["email"]
    customer_id = existing_customer["id"]

    logger.info(
        "📧 Existing customer created: ID=%r, email=%r",
        customer_id,
        email,
    )

    # ------------------------------------------------------------------
    # Step 2 — Arrange: build the intentionally invalid duplicate payload
    # ------------------------------------------------------------------
    # The email is valid in isolation but invalid for this operation because
    # it already belongs to an existing WooCommerce customer.
    payload = {
        "email": email,
        "password": "Password1",
    }

    logger.info(
        "⚠️ Attempting to create a duplicate customer using existing email: %r",
        email,
    )

    # ------------------------------------------------------------------
    # Step 3 — Act: attempt duplicate customer creation
    # ------------------------------------------------------------------
    http_response = customer_api_raw.post(
        endpoint="customers",
        payload=payload,
    )

    response = http_response.json

    # ------------------------------------------------------------------
    # Step 4 — Assert: transport-level validation
    # ------------------------------------------------------------------
    assert http_response.status_code == 400, (
        f"Expected 400 for duplicate customer email, "
        f"got {http_response.status_code}. "
        f"Response: {http_response.text[:300]}"
    )

    # ------------------------------------------------------------------
    # Step 5 — Assert: business-level validation
    # ------------------------------------------------------------------
    assert_customer_creation_failed(response)

    # ------------------------------------------------------------------
    # Step 6 — Assert: original customer still exists through the API
    # ------------------------------------------------------------------
    api_customers = customer_helper.list_customers_paginated(email=email)

    # ------------------------------------------------------------------
    # Step 7 — Assert: original customer still exists in the database
    #        and API/DB data remains consistent
    # ------------------------------------------------------------------
    db_customer = customers_dao.get_customer_by_email(email=email)

    assert_customer_exists_and_matches_api(
        api_customers,
        email,
        db_customer,
    )

    # ------------------------------------------------------------------
    # Step 8 — Assert: error response follows the API error contract
    # ------------------------------------------------------------------
    validate(
        instance=response,
        schema=error_schema,
    )

    logger.info(
        "✅ Duplicate customer creation correctly rejected: " "%s → %s: %s",
        payload,
        response["code"],
        response["message"],
    )
