# config_loader.py

"""
Resolve service-specific configuration for the active test run.

This module is responsible for determining which entity (customers,
products, orders, coupons, etc.) is being tested and returning the
correct configuration for that entity.

Responsibilities:
- Detect the active service automatically or from the SERVICE environment variable.
- Load the matching config_<service>.py module.
- Resolve the API base URL for the current execution environment.
- Provide database connection settings from environment variables.

This module does NOT read framework behaviour settings such as logging,
reporting or feature flags. Those are owned by runtime_config.py.

Think of the configuration flow like this:

    runtime_config.py
            │
            ▼
    config_loader.py
            │
            ▼
    APIClient / Helpers / Plugins / Tests

Edit this file when:
- adding a new service discovery rule,
- changing how API hosts are resolved,
- changing database configuration loading.

Do not edit this file to add new runtime flags or feature toggles.
Those belong in runtime_config.py.

"""

from __future__ import annotations

import os
import importlib
from pathlib import Path
from functools import lru_cache
from typing import Dict, Any, Optional
from dotenv import load_dotenv
from EcommerceAPI.src.configs.runtime_config import get_config

# Always load .env (safe no-op if missing)
load_dotenv()


# =====================================================================
#  Auto-detect microservice based on working directory
# =====================================================================


@lru_cache(maxsize=None)
def detect_service() -> str:
    """
    Determine which service the current pytest run is targeting.

    The framework normally detects the service automatically from the test
    directory. For example:

        tests/customers/
        tests/products/
        tests/orders/

    If automatic detection is not possible, the SERVICE environment
    variable can be used as an explicit override.

    The detected service is later used to load the matching
    config_<service>.py file.

    Returns:
        Service name in lowercase.

    Raises:
        RuntimeError if the service cannot be determined.
    """
    # 1) Environment override
    svc_env = os.getenv("SERVICE")
    if svc_env:
        return svc_env.lower()

    cwd = Path.cwd()

    # 2) If cwd path includes tests/<service>/..., extract that service first
    parts = cwd.parts
    for idx, part in enumerate(parts[:-1]):
        if part == "tests" and idx + 1 < len(parts):
            candidate = parts[idx + 1]
            candidate_path = Path(*parts[: idx + 2])
            if _config_module_exists(candidate_path):
                return candidate.lower()
            # fallback: still keep candidate for later verification

    # 3) Walk ancestors to find a 'tests' directory with service configs
    candidates = _find_service_candidates_from_ancestors(cwd)
    if not candidates:
        raise RuntimeError(
            "Unable to auto-detect microservice. No 'tests/<service>/configs/config_<service>.py' "
            "modules were found in the current working directory or any parent directories. "
            "Please set the SERVICE environment variable to the target service (e.g. export SERVICE=customers) "
            "or run tests from the repository root."
        )

    # If only one candidate, return it
    if len(candidates) == 1:
        return next(iter(candidates)).lower()

    # If multiple candidates, try to pick one that matches cwd path
    for cand in candidates:
        if f"/tests/{cand}/" in str(cwd) or str(cwd).endswith(f"/tests/{cand}"):
            return cand.lower()

    # Ambiguous: present helpful error listing candidates
    sorted_list = sorted(candidates)
    raise RuntimeError(
        "Multiple microservice candidates found but none could be unambiguously selected.\n"
        f"Candidates: {sorted_list}\n"
        "Please set the SERVICE environment variable to one of the above (e.g. export SERVICE=customers)."
    )


def _find_service_candidates_from_ancestors(start: Path) -> set[str]:
    """
    Search parent directories for available services.

    The framework walks from the current working directory towards the
    repository root looking for folders that match the expected layout:

        tests/<service>/configs/config_<service>.py

    Every matching service is collected and returned.

    Returns:
        A set of candidate service names (possibly empty).
    """
    found: set[str] = set()
    for ancestor in [start] + list(start.parents):
        tests_dir = ancestor / "tests"
        if tests_dir.is_dir():
            for entry in tests_dir.iterdir():
                if entry.is_dir():
                    cfg = entry / "configs" / f"config_{entry.name}.py"
                    if cfg.exists():
                        found.add(entry.name)
        # stop early if we found at least one candidate in this ancestor
        if found:
            return found
    return found


def _config_module_exists(path: Path) -> bool:
    """
    Check whether a valid service configuration exists.

    A service is considered valid when it contains:

        tests/<service>/configs/config_<service>.py

    This helper is used during automatic service discovery.
    """
    path = path.resolve()
    # if path itself is tests/<service> (i.e., path.parts ends with ['tests','<service>'])
    if path.name and path.parent.name == "tests":
        service = path.name
        return (path / "configs" / f"config_{service}.py").exists()

    # otherwise, try path/tests/*
    tests_dir = path / "tests"
    if tests_dir.is_dir():
        for entry in tests_dir.iterdir():
            if (
                entry.is_dir()
                and (entry / "configs" / f"config_{entry.name}.py").exists()
            ):
                return True
    return False


# =====================================================================
#  SECTION 3: Dynamic import of per-service config
# =====================================================================


@lru_cache(maxsize=None)
def load_service_config(service: str):
    """
    Load the configuration module for a service.

    Each service owns its own configuration file that contains public,
    non-sensitive settings such as API endpoint mappings.

    Example:

        tests/products/configs/config_products.py

    Expected layout:
        tests/<service>/configs/config_<service>.py

    The module must define:
        API_HOSTS = { "test": "...", "prod": "..." }

    Args:
        service: microservice name, e.g. "customers"

    Returns:
        Imported module

    Raises:
        ImportError if config module missing or malformed.
    """
    service = service.lower()
    module_path = f"tests.{service}.configs.config_{service}"

    try:
        module = importlib.import_module(module_path)
    except Exception as exc:
        raise ImportError(
            f"Failed to import config module for service '{service}'. "
            f"Expected module: {module_path}"
        ) from exc

    # Basic validation of the module shape
    if not hasattr(module, "API_HOSTS"):
        raise ImportError(
            f"Config module '{module_path}' does not define 'API_HOSTS'. "
            "Please ensure API_HOSTS is present and is a mapping from ENV->URL."
        )
    if not isinstance(getattr(module, "API_HOSTS"), dict):
        raise ImportError(
            f"'API_HOSTS' in module '{module_path}' must be a dict mapping env->url."
        )

    return module


# =====================================================================
#  SECTION 4: API Host Resolution
# =====================================================================


def get_api_host(service: Optional[str] = None) -> str:
    """
    Return the API base URL for the active execution environment.

    The URL is resolved in three steps:

    1. Determine which service is being tested.
    2. Load that service's API_HOSTS mapping.
    3. Return the URL that matches the active API_ENV.

    Example:

        API_ENV=local
            ↓
        config_products.py
            ↓
        API_HOSTS["local"]
            ↓
        http://localhost:8888/...

    This keeps environment-specific URLs out of the framework logic.

    Args:
        service: optional override. If not provided, auto-detect is used.

    Returns:
        Base URL as a string.

    Raises:
        RuntimeError if API_HOSTS missing or ENV not found in API_HOSTS.
    """
    service = (service or detect_service()).lower()

    module = load_service_config(service)

    hosts = getattr(module, "API_HOSTS", None)
    if hosts is None:
        raise RuntimeError(f"Config module for '{service}' does not define API_HOSTS")

    cfg = get_config()
    env = cfg.ENV.lower()

    if env not in hosts:
        raise RuntimeError(f"ENV='{env}' missing from API_HOSTS in config_{service}")

    return hosts[env]


# =====================================================================
#  SECTION 5: DB Configuration (secure from .env only)
# =====================================================================


def get_db_config() -> Dict[str, Any]:
    """
    Load database connection settings from environment variables.

    Database credentials are intentionally never stored in the repository.

    Instead, they are supplied through:

    - .env for local development
    - CI secrets for automated pipelines

    Only values that exist are returned.

    Supported vars:
        DB_HOST
        DB_USER
        DB_PASS
        DB_NAME
        DB_PORT
        DB_SOCKET

    Returns:
        A dictionary with populated values (missing values omitted).
    """

    def get(key: str) -> Optional[str]:
        val = os.getenv(key)
        return val if val not in ("", None) else None

    cfg = {
        "host": get("DB_HOST"),
        "user": get("DB_USER"),
        "password": get("DB_PASS"),
        "database": get("DB_NAME"),
        "port": get("DB_PORT"),
        "socket": get("DB_SOCKET"),
    }

    return {k: v for k, v in cfg.items() if v is not None}


# =====================================================================
#  SECTION 6: Unified Config Object (Convenience)
# =====================================================================


def get_loader_config() -> Dict[str, Any]:
    """
    Build a convenience configuration dictionary.

    This helper combines the most commonly used values into a single
    dictionary so callers do not need to query several helper functions.

    It is mainly intended for debugging and lightweight integrations..

    {
        "service": "customers",
        "api_host": "...",
        "db": {...},
    }
    """
    service = detect_service()
    return {
        "service": service,
        "api_host": get_api_host(service),
        "db": get_db_config(),
    }


# =====================================================================
#  SECTION 7: Minimal debug helper
# =====================================================================


def debug_print() -> None:
    """
    Print the resolved configuration to the console.

    Useful when diagnosing configuration or environment issues during
    local development.

    This function is intended for debugging only.
    """
    c = get_loader_config()
    print("=== Framework Config ===")
    for k, v in c.items():
        print(f"{k}: {v}")
