from __future__ import annotations

from typing import Any

from EcommerceAPI.src.test_data.factories.base import BaseFactory
from EcommerceAPI.src.utils.generic_utilities import (
    generate_random_address,
    generate_random_email,
    generate_random_first_name,
    generate_random_last_name,
    generate_random_password,
    generate_random_username,
)


class CustomerFactory(BaseFactory[dict[str, Any]]):
    """
    Factory responsible for generating valid customer creation data.

    A factory belongs to the test-data generation layer. Its job is to
    create a complete, valid set of data in memory so tests do not have
    to manually assemble repetitive payloads.

    IMPORTANT ARCHITECTURAL RULE
    ----------------------------
    This factory generates *creation data*. It does not represent the
    Customer object returned by WooCommerce.

    The canonical Customer API model lives in the customer domain:

        EcommerceAPI/src/customers/models/customer_model.py

    That model describes API responses and contains server-generated fields
    such as ``id``. It should therefore not be used as this factory's
    return type.

    Instead, this factory returns ``dict[str, Any]`` containing fields
    needed to create a customer. The provisioner will later pass this data
    to the existing customer domain helper.

    RESPONSIBILITIES
    ----------------
    - Generate realistic test values.
    - Generate collision-resistant values where uniqueness is required.
    - Provide sensible defaults for a complete customer.
    - Accept explicit overrides for scenario-specific data.

    NON-RESPONSIBILITIES
    --------------------
    The factory must NOT:
    - call the WooCommerce API;
    - access the database;
    - use pytest fixtures;
    - register resources for cleanup;
    - perform provisioning;
    - validate API responses;
    - contain test assertions.

    Keeping these responsibilities separate makes the factory reusable
    from API, GraphQL, and UI-data workflows without coupling it to pytest
    or to a particular execution layer.
    """

    def build(self, **overrides: Any) -> dict[str, Any]:
        """
        Build a complete customer creation payload.

        The factory generates generic primitive values through the shared
        utility layer and composes them into the customer structure.

        Explicit keyword arguments replace generated defaults, allowing a
        test to customize only the data relevant to its scenario.

        Example:
            customer = factory.build()

        Or, when a known email is required:

            customer = factory.build(email="known@example.com")

        Args:
            **overrides:
                Supported creation fields:
                ``email``, ``password``, ``username``, ``first_name``,
                ``last_name``, ``billing`` and ``shipping``.

        Returns:
            dict[str, Any]:
                Complete customer creation data.

        Raises:
            TypeError:
                If an unsupported field is supplied.
        """
        values = dict(overrides)

        # Generate names first because the default username and addresses
        # depend on them.
        first_name = values.pop(
            "first_name",
            generate_random_first_name(),
        )
        last_name = values.pop(
            "last_name",
            generate_random_last_name(),
        )

        # Credentials are generated by the shared utility layer rather than
        # by a second random-data library. Explicit values always win.
        email = values.pop(
            "email",
            generate_random_email(),
        )
        password = values.pop(
            "password",
            generate_random_password(),
        )

        username = values.pop(
            "username",
            generate_random_username(first_name, last_name),
        )

        # The utility returns generic address primitives. The factory adds
        # customer-specific fields such as first/last name and billing email.
        billing = values.pop(
            "billing",
            self._build_address(
                generate_random_address(country="ES"),
                first_name,
                last_name,
                email,
            ),
        )
        shipping = values.pop(
            "shipping",
            self._build_address(
                generate_random_address(country="ES"),
                first_name,
                last_name,
            ),
        )

        if values:
            unknown_fields = ", ".join(sorted(values))
            raise TypeError(f"Unsupported CustomerFactory fields: {unknown_fields}")

        return {
            "email": email,
            "password": password,
            "username": username,
            "first_name": first_name,
            "last_name": last_name,
            "billing": billing,
            "shipping": shipping,
        }

    @staticmethod
    def _build_address(
        address: dict[str, str],
        first_name: str,
        last_name: str,
        email: str | None = None,
    ) -> dict[str, str]:
        """
        Add customer-specific fields to a generic generated address.

        Keeping this small composition step in the domain factory is
        intentional: generic utilities generate reusable primitives, while
        the CustomerFactory knows what WooCommerce customer address data
        should look like.
        """
        customer_address = {
            "first_name": first_name,
            "last_name": last_name,
            **address,
        }

        if email is not None:
            customer_address["email"] = email

        return customer_address

    # Username and address generation intentionally live in the shared
    # utility layer as reusable data-generation primitives. This factory
    # composes those primitives into the WooCommerce customer structure.
